### ISSUE TITLE
Another dataset

### ISSUE THREAD

**Issue by ngragaei** [peerdavid/gamma-capsule-network#2]
Can i use speech instead of images? how?

**Comment by peerdavid** [comment]
I'm not an expert with speech recognition, but I think it depends on the dimensionality of the data:  In [1] input features in frequency and time axes are used, so it should be directly applicable for gamma capsule networks, if inputs are of shape (batch_size, time, frequency, 1). If the input dimensionality is different, the first convolutional layer as well as the primary capsule layer must be adapted accordingly. Higher level gamma capsules and SDA routing should then be similar.

[1] Bae et al. "End-to-End Speech Command Recognition with Capsule Network" (2018)

**Comment by peerdavid** [comment]
Due to inactivity, I will close this issue now.
